version: "3.9"

services:
  frontend:
    image: molinacont18/ptrello-frontend:latest
    container_name: ptrello_frontend_prod
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    image: molinacont18/ptrello-backend:latest
    container_name: ptrello_backend_prod
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    volumes:
      - uploads:/app/public/img/projects
    restart: unless-stopped

volumes:
  uploads:
